---

name: Action self-check / smoke-test

on:
  push:
  pull_request:
  workflow_dispatch:

permissions: {}

jobs:
  failing-job:
    runs-on: ubuntu-latest
    steps:
    - run: exit 1

  succeeding-job:
    runs-on: ubuntu-latest
    steps:
    - run: exit 0

  skipped-job:
    if: false
    runs-on: ubuntu-latest
    steps:
    - run: exit 0

  partially-failing-partially-skipped-matrix:
    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.rc == '1' }}
    strategy:
      matrix:
        rc:
        - 0
        - 1
        - 2
    steps:
    - if: matrix.rc != '2'
      env:
        MATRIX_RC: ${{ matrix.rc }}
      run: exit "$MATRIX_RC"

  wait-for-success:
    needs:
    - succeeding-job
    - skipped-job
    if: always()
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the src from Git
      uses: actions/checkout@a37ce9120846195fa4ece8f58b268e6043cb2f26 # v3
    - env:
        RESULTS: ${{ toJSON(needs.*.result) }}
      run: echo "results=$RESULTS"
    - uses: ./
      id: check
      continue-on-error: true
      with:
        jobs: ${{ toJSON(needs) }}
    - name: Fail on unexpected outcome (assertion step)
      run: exit 1
      if: steps.check.outcome != 'failure'
    - env:
        OUTPUTS: ${{ toJSON(steps.check.outputs) }}
      run: echo "outputs=$OUTPUTS"
      if: always()

  wait-for-failure:
    needs:
    - failing-job
    - skipped-job
    if: always()
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the src from Git
      uses: actions/checkout@a37ce9120846195fa4ece8f58b268e6043cb2f26 # v3
    - env:
        RESULTS: ${{ toJSON(needs.*.result) }}
      run: echo "results=$RESULTS"
    - uses: ./
      id: check
      continue-on-error: true
      with:
        jobs: ${{ toJSON(needs) }}
    - name: Fail on unexpected outcome (assertion step)
      run: exit 1
      if: steps.check.outcome != 'failure'
    - env:
        OUTPUTS: ${{ toJSON(steps.check.outputs) }}
      run: echo "outputs=$OUTPUTS"
      if: always()

  wait-for-both:
    needs:
    - failing-job
    - succeeding-job
    - skipped-job
    if: always()
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the src from Git
      uses: actions/checkout@a37ce9120846195fa4ece8f58b268e6043cb2f26 # v3
    - env:
        RESULTS: ${{ toJSON(needs.*.result) }}
      run: echo "results=$RESULTS"
    - uses: ./
      id: check
      continue-on-error: true
      with:
        jobs: ${{ toJSON(needs) }}
    - name: Fail on unexpected outcome (assertion step)
      run: exit 1
      if: steps.check.outcome != 'failure'
    - env:
        OUTPUTS: ${{ toJSON(steps.check.outputs) }}
      run: echo "outputs=$OUTPUTS"
      if: always()

  allow-some-failures:
    needs:
    - failing-job
    - succeeding-job
    - skipped-job
    if: always()
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the src from Git
      uses: actions/checkout@a37ce9120846195fa4ece8f58b268e6043cb2f26 # v3
    - env:
        RESULTS: ${{ toJSON(needs.*.result) }}
      run: echo "results=$RESULTS"
    - uses: ./
      id: check
      continue-on-error: true
      with:
        allowed-failures: >-
          ["failing-job", "skipped-job"]
        jobs: ${{ toJSON(needs) }}
    - name: Fail on unexpected outcome (assertion step)
      run: exit 1
      if: steps.check.outcome != 'success'
    - env:
        OUTPUTS: ${{ toJSON(steps.check.outputs) }}
      run: echo "outputs=$OUTPUTS"
      if: always()

  allow-some-failures-str:
    needs:
    - failing-job
    - succeeding-job
    - skipped-job
    if: always()
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the src from Git
      uses: actions/checkout@a37ce9120846195fa4ece8f58b268e6043cb2f26 # v3
    - env:
        RESULTS: ${{ toJSON(needs.*.result) }}
      run: echo "results=$RESULTS"
    - uses: ./
      id: check
      continue-on-error: true
      with:
        allowed-failures: failing-job, skipped-job
        jobs: ${{ toJSON(needs) }}
    - name: Fail on unexpected outcome (assertion step)
      run: exit 1
      if: steps.check.outcome != 'success'
    - env:
        OUTPUTS: ${{ toJSON(steps.check.outputs) }}
      run: echo "outputs=$OUTPUTS"
      if: always()

  allow-failures-n-skips:
    needs:
    - failing-job
    - succeeding-job
    - skipped-job
    if: always()
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the src from Git
      uses: actions/checkout@a37ce9120846195fa4ece8f58b268e6043cb2f26 # v3
    - env:
        RESULTS: ${{ toJSON(needs.*.result) }}
      run: echo "results=$RESULTS"
    - uses: ./
      id: check
      continue-on-error: true
      with:
        allowed-failures: failing-job
        allowed-skips: skipped-job
        jobs: ${{ toJSON(needs) }}
    - name: Fail on unexpected outcome (assertion step)
      run: exit 1
      if: steps.check.outcome != 'success'
    - env:
        OUTPUTS: ${{ toJSON(steps.check.outputs) }}
      run: echo "outputs=$OUTPUTS"
      if: always()

  allow-skips:
    needs:
    - failing-job
    - succeeding-job
    - skipped-job
    if: always()
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the src from Git
      uses: actions/checkout@a37ce9120846195fa4ece8f58b268e6043cb2f26 # v3
    - env:
        RESULTS: ${{ toJSON(needs.*.result) }}
      run: echo "results=$RESULTS"
    - uses: ./
      id: check
      continue-on-error: true
      with:
        allowed-skips: failing-job, skipped-job
        jobs: ${{ toJSON(needs) }}
    - name: Fail on unexpected outcome (assertion step)
      run: exit 1
      if: steps.check.outcome != 'failure'
    - env:
        OUTPUTS: ${{ toJSON(steps.check.outputs) }}
      run: echo "outputs=$OUTPUTS"
      if: always()

  allow-partials:
    needs:
    - failing-job
    - succeeding-job
    - skipped-job
    - partially-failing-partially-skipped-matrix
    if: always()
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the src from Git
      uses: actions/checkout@a37ce9120846195fa4ece8f58b268e6043cb2f26 # v3
    - env:
        RESULTS: ${{ toJSON(needs.*.result) }}
      run: echo "results=$RESULTS"
    - uses: ./
      id: check
      continue-on-error: true
      with:
        allowed-failures: failing-job
        allowed-skips: skipped-job
        jobs: ${{ toJSON(needs) }}
    - name: Fail on unexpected outcome (assertion step)
      run: exit 1
      if: steps.check.outcome != 'success'
    - env:
        OUTPUTS: ${{ toJSON(steps.check.outputs) }}
      run: echo "outputs=$OUTPUTS"
      if: always()

  check:
    needs:
    - wait-for-success
    - wait-for-failure
    - wait-for-both
    - allow-some-failures
    - allow-some-failures-str
    - allow-failures-n-skips
    - allow-skips
    - allow-partials
    if: always()
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the src from Git
      uses: actions/checkout@a37ce9120846195fa4ece8f58b268e6043cb2f26 # v3
    - uses: ./
      id: check
      with:
        jobs: ${{ toJSON(needs) }}

...
